### ISSUE TITLE
Tries to install mmseqs, should be mmseqs2

### ISSUE THREAD

**Issue by iquasere** [PedroMTQ/refdb_generator#1]
Greetings!

I am now trying to install databases using this functionality. I first edited the yaml, since it asks for ```mmseqs``` [where](https://github.com/PedroMTQ/refdb_generator/blob/main/reference_generator.yml#L14) it should ask for ```mmseqs2```.

Next I tried running ```python refdb_generator/Reference_Generator.py -o path/to/output_folder -db swissprot``` and got ```FileNotFoundError: [Errno 2] No such file or directory: '/resources_directory/hmms'```. This tells me it is trying to use absolute paths, and using an absolute path works, but maybe you could allow it to use relative paths as well.

Finally, I wanted to ask if this is application alters in any way UniProt's database, or if it just downloads it. What is in the ```metadata.tsv``` file?

**Comment by PedroMTQ** [comment]
Hello  @iquasere 
Thanks for letting me know, I'll change the yaml file.
Yeah sure, I can add the option to use relative paths.

The metadata.tsv contains the cross-linking included in the uniprot.dat file (downloaded from uniprot). 
So basically the seqs from Trembl or SwissProt  (depending on which one you chose) followed by the associated metadata:
seq_id | db:db_id...

This is then used by Mantis to add the metadata to the respective hits, etc (just like with the default references)

I'm not sure what you mean "alters in any way UniProt's database". 
It just extracts the sequences from uniprot.dat into a merged faa and creates a diamond database (and the metadata.tsv)

Regards,
Pedro
